// frontend/src/admin/App.jsx
import { useEffect, useState } from "react";

import { ErrorBoundary } from "./components/ErrorBoundary.jsx";
import WorkspaceNav from "./components/WorkspaceNav.jsx";
import { Loader, Notice, StatusPill } from "./components/ui.jsx";
import { usePanel } from "./state/PanelProvider.jsx";
import CommerceWorkspace from "./workspaces/CommerceWorkspace.jsx";
import DeliveryWorkspace from "./workspaces/DeliveryWorkspace.jsx";
import DiagnosticsWorkspace from "./workspaces/DiagnosticsWorkspace.jsx";
import HostsWorkspace from "./workspaces/HostsWorkspace.jsx";
import ObservabilityWorkspace from "./workspaces/ObservabilityWorkspace.jsx";
import OverviewWorkspace from "./workspaces/OverviewWorkspace.jsx";
import RoutingWorkspace from "./workspaces/RoutingWorkspace.jsx";
import TrafficWorkspace from "./workspaces/TrafficWorkspace.jsx";

// The console is organized around the incident questions: what the hosts are
// doing, what the traffic looks like, and what to check after a failure.
const WORKSPACES = [
  { key: "overview", label: "总览", description: "健康、路径与待处理", blurb: "先确认系统健康、当前路径和待处理，再进入具体操作。" },
  { key: "hosts", label: "主机", description: "数据面与纳管节点", blurb: "每台纳管主机的角色、管理通道、运行时状态与可用操作。" },
  { key: "traffic", label: "流量", description: "日流量与端口负载", blurb: "累计流量、日粒度历史、端口负载排行与单端口明细。" },
  { key: "diagnostics", label: "故障排查", description: "探测、切换与体检", blurb: "按顺序核对探测记录、DNS 切换事件和数据面体检结果。" },
  { key: "routing", label: "AI 路由", description: "出口、探测与切换", blurb: "解释当前 AI 出口、候选健康、人工策略和故障切换。" },
  { key: "delivery", label: "交付", description: "端口与租户凭据", blurb: "管理监听入口、租户配额与每个端口的独立订阅凭据。" },
  { key: "commerce", label: "订单与套餐", description: "售卖、审核与开通", blurb: "管理套餐、订单审核与自动开通。" },
  { key: "observe", label: "可观测", description: "Prometheus 与 Grafana", blurb: "从指标和 Grafana 深入排查资源与流量异常。" },
];

const WORKSPACE_COMPONENTS = {
  overview: OverviewWorkspace,
  hosts: HostsWorkspace,
  traffic: TrafficWorkspace,
  diagnostics: DiagnosticsWorkspace,
  routing: RoutingWorkspace,
  delivery: DeliveryWorkspace,
  commerce: CommerceWorkspace,
  observe: ObservabilityWorkspace,
};

export default function App() {
  const panel = usePanel();
  const [activeWorkspace, setActiveWorkspace] = useState("overview");
  const [isMobile, setIsMobile] = useState(false);
  const [mobileNavOpen, setMobileNavOpen] = useState(false);

  useEffect(() => {
    function updateIsMobile() {
      const mobile = typeof window !== "undefined" && window.innerWidth <= 840;
      setIsMobile(mobile);
      if (!mobile) setMobileNavOpen(false);
    }
    updateIsMobile();
    window.addEventListener("resize", updateIsMobile);
    return () => window.removeEventListener("resize", updateIsMobile);
  }, []);

  const meta = WORKSPACES.find((item) => item.key === activeWorkspace) || WORKSPACES[0];
  const ActiveWorkspace = WORKSPACE_COMPONENTS[activeWorkspace];
  const badges = {
    diagnostics: panel.insights?.probes?.recent_failures?.length || 0,
    commerce: panel.commerce.summary.pending_review_count || 0,
  };
  const lastRefreshLabel =
    panel.meta?.dashboard_updated_at_display || panel.meta?.updated_at_display || "自动刷新 15 秒";

  function selectWorkspace(key) {
    setActiveWorkspace(key);
    setMobileNavOpen(false);
  }

  return (
    <div className="admin-shell">
      <aside className={`admin-sidebar${mobileNavOpen ? " is-open" : ""}`} aria-label="控制台导航">
        <div className="sidebar-scroll">
          <div className="brand-lockup">
            <div className="brand-mark" aria-hidden="true">XR</div>
            <div>
              <p className="brand-kicker">ROUTING PANEL</p>
              <strong>Control Center</strong>
            </div>
          </div>
          <p className="brand-description">主机、流量与故障排查的一体化控制面。</p>
          <WorkspaceNav items={WORKSPACES} activeKey={activeWorkspace} onSelect={selectWorkspace} badges={badges} />
          <div className="sidebar-status-stack">
            <div className="sidebar-status-card">
              <div className="sidebar-status-card__head">
                <span>DATA PLANE</span>
                <i className={panel.dataPlaneStatus?.xray_running ? "is-ok" : "is-bad"} />
              </div>
              <strong>{panel.dataPlaneRunningLabel()}</strong>
              <small>{panel.dataPlaneStatus?.management_target || "当前未配置数据面"}</small>
            </div>
            <div className="sidebar-status-card">
              <div className="sidebar-status-card__head">
                <span>AI NODE</span>
                <i className={panel.aiNodeStatus?.reachable ? "is-ok" : "is-warn"} />
              </div>
              <strong>{panel.aiNodeStatus?.reachable ? "可达" : "待确认"}</strong>
              <small>{panel.aiNodeStatus?.management_target || "AI 节点未纳管"}</small>
            </div>
          </div>
        </div>
        <div className="sidebar-footer">
          <span>CONTROL PLANE</span>
          <strong>{panel.meta?.panel_address || "—"}</strong>
          <small>{panel.meta?.timezone_label || "服务器本地时区"}</small>
        </div>
      </aside>

      {isMobile && mobileNavOpen ? (
        <button className="mobile-scrim" type="button" aria-label="关闭导航" onClick={() => setMobileNavOpen(false)} />
      ) : null}

      <div className="admin-main">
        <header className="admin-topbar">
          <div className="topbar-title">
            {isMobile ? (
              <button
                className="icon-button mobile-menu-button"
                type="button"
                aria-label="打开控制台导航"
                onClick={() => setMobileNavOpen((open) => !open)}
              >
                <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 6h16M4 12h16M4 18h16" /></svg>
              </button>
            ) : null}
            <div>
              <p className="breadcrumb">
                CONTROL CENTER <span>/</span> {meta.label}
              </p>
              <h1>{meta.label}</h1>
              <p>{meta.blurb}</p>
            </div>
          </div>
          <div className="topbar-actions">
            <div className="live-indicator">
              <span className={`live-dot${panel.loading ? " is-busy" : ""}`} />
              <span>{panel.loading ? "同步中" : lastRefreshLabel}</span>
            </div>
            <StatusPill
              tone={panel.dataPlaneStatus?.xray_running ? "success" : "danger"}
              label={panel.dataPlaneRunningLabel()}
            />
            <button
              className="icon-button"
              type="button"
              aria-label={panel.loading ? "正在刷新" : "刷新数据"}
              disabled={panel.loading}
              onClick={() => panel.refreshDashboard()}
            >
              <svg viewBox="0 0 24 24" aria-hidden="true">
                <path d="M20 11a8.1 8.1 0 0 0-14.9-3M4 5v4h4M4 13a8.1 8.1 0 0 0 14.9 3M20 19v-4h-4" />
              </svg>
            </button>
          </div>
        </header>

        <main className="admin-content">
          <Notice message={panel.flash.message} level={panel.flash.level} onClose={panel.clearFlash} />
          <Loader show={panel.loading} />
          <ErrorBoundary>
            <ActiveWorkspace onOpenWorkspace={selectWorkspace} />
          </ErrorBoundary>
        </main>
      </div>
    </div>
  );
}

// frontend/src/admin/App.vue
<script>
import { NConfigProvider } from "naive-ui/es/config-provider";
import { NSpin } from "naive-ui/es/spin";

import { AiDomainsMixin } from "../mixins/domains.js";
import { CommerceMixin } from "../mixins/commerce.js";
import { CoreMixin } from "../mixins/core.js";
import { DnsMixin } from "../mixins/dns.js";
import { PortsMixin } from "../mixins/ports.js";
import StatusPill from "../shared/ui/StatusPill.vue";
import { naiveThemeOverrides } from "../shared/tokens.js";
import WorkspaceNav from "./components/WorkspaceNav.vue";
import AiRoutingSection from "./sections/AiRoutingSection.vue";
import CommerceSection from "./sections/CommerceSection.vue";
import InfraSection from "./sections/InfraSection.vue";
import MonitoringSection from "./sections/MonitoringSection.vue";
import OverviewSection from "./sections/OverviewSection.vue";
import PortsSection from "./sections/PortsSection.vue";
import TrafficSection from "./sections/TrafficSection.vue";

export default {
  name: "AdminApp",
  components: {
    AiRoutingSection,
    CommerceSection,
    InfraSection,
    MonitoringSection,
    NConfigProvider,
    NSpin,
    OverviewSection,
    PortsSection,
    StatusPill,
    TrafficSection,
    WorkspaceNav,
  },
  mixins: [CoreMixin, PortsMixin, CommerceMixin, DnsMixin, AiDomainsMixin],
  provide() {
    return { panel: this };
  },
  data() {
    return {
      themeOverrides: naiveThemeOverrides(),
      activeWorkspace: "overview",
      isMobile: false,
      mobileNavOpen: false,
      loading: true,
      dashboardPollTimer: null,
      dashboardRefreshBusy: false,
      authEnabled: Boolean(typeof window !== "undefined" && window.__BOOT__ && window.__BOOT__.auth_enabled),
      workspaceOptions: [
        { key: "overview", label: "Overview", description: "系统健康与待处理" },
        { key: "routing", label: "AI Routing", description: "出口、探测与切换" },
        { key: "traffic", label: "Traffic", description: "流量、端口与连接" },
        { key: "resources", label: "Resources", description: "端口与租户交付" },
        { key: "commerce", label: "Orders & Plans", description: "订单、套餐与审核" },
        { key: "infra", label: "Infrastructure", description: "节点、DNS 与运行时" },
        { key: "observe", label: "Observability", description: "Prometheus 与 Grafana" },
      ],
    };
  },
  computed: {
    dataPlaneTone() {
      return this.dataPlaneStatus && this.dataPlaneStatus.xray_running ? "success" : "danger";
    },
    activeWorkspaceMeta() {
      return this.workspaceOptions.find((item) => item.key === this.activeWorkspace) || this.workspaceOptions[0];
    },
    workspaceTitle() {
      return this.activeWorkspaceMeta.label;
    },
    workspaceDescription() {
      return {
        overview: "先确认系统健康、当前路径和待处理，再进入具体操作。",
        routing: "解释当前 AI 出口、候选健康、人工策略和故障切换。",
        traffic: "观察累计流量、连接和主要端口负载。",
        resources: "管理监听入口、租户交付和订阅凭据。",
        commerce: "管理套餐、订单审核与服务开通。",
        infra: "检查数据面、AI 节点、DNS 与运行时状态。",
        observe: "从指标和 Grafana 深入排查资源与流量异常。",
      }[this.activeWorkspace] || "";
    },
    lastRefreshLabel() {
      return this.meta?.dashboard_updated_at_display || this.meta?.updated_at_display || "自动刷新 15 秒";
    },
  },
  async mounted() {
    this.updateIsMobile();
    if (typeof window !== "undefined") {
      window.addEventListener("resize", this.updateIsMobile);
    }
    const boot = (typeof window !== "undefined" && window.__BOOT__) || {};
    this.meta = { csrf_token: boot.csrf_token || "" };
    try {
      const data = await this.requestJson("/api/dashboard");
      this.applyDashboard(data.dashboard || {});
      if (import.meta.env.MODE !== "test") {
        this.dashboardPollTimer = window.setInterval(this.refreshDashboard, 15000);
      }
    } catch (error) {
      this.setFlash(error.message || "加载失败。", "error");
    } finally {
      this.loading = false;
    }
  },
  beforeUnmount() {
    if (this.dashboardPollTimer) {
      window.clearInterval(this.dashboardPollTimer);
      this.dashboardPollTimer = null;
    }
    if (this.topologyTransitionTimer) {
      window.clearTimeout(this.topologyTransitionTimer);
      this.topologyTransitionTimer = null;
    }
    if (typeof window !== "undefined") {
      window.removeEventListener("resize", this.updateIsMobile);
    }
  },
  methods: {
    updateIsMobile() {
      const mobile = typeof window !== "undefined" && window.innerWidth <= 840;
      this.isMobile = mobile;
      if (!mobile) this.mobileNavOpen = false;
    },
    selectWorkspace(key) {
      this.activeWorkspace = key;
      this.mobileNavOpen = false;
    },
    toggleMobileNav() {
      this.mobileNavOpen = !this.mobileNavOpen;
    },
    async refreshNow() {
      await this.refreshDashboard();
    },
    async refreshDashboard() {
      if (this.dashboardRefreshBusy || this.loading) return;
      this.dashboardRefreshBusy = true;
      try {
        const data = await this.requestJson("/api/dashboard");
        this.applyDashboard(data.dashboard || {});
      } catch (_error) {
        // Keep the last known state visible when a background refresh fails.
      } finally {
        this.dashboardRefreshBusy = false;
      }
    },
    logout() {
      const form = document.createElement("form");
      form.method = "post";
      form.action = "/logout";
      document.body.appendChild(form);
      form.submit();
    },
  },
};
</script>

<template>
  <n-config-provider :theme-overrides="themeOverrides">
    <div class="admin-shell">
      <aside class="admin-sidebar" :class="{ 'is-open': mobileNavOpen }" aria-label="控制台导航">
        <div class="sidebar-scroll">
          <div class="brand-lockup">
            <div class="brand-mark" aria-hidden="true">XR</div>
            <div>
              <p class="brand-kicker">ROUTING PANEL</p>
              <strong>Control Center</strong>
            </div>
          </div>
          <p class="brand-description">AI 路由、网络流量、租户与运营的一体化控制面。</p>

          <workspace-nav :items="workspaceOptions" :active-key="activeWorkspace" @select="selectWorkspace" />

          <div class="sidebar-status-stack" aria-label="基础设施状态">
            <div class="sidebar-status-card">
              <div class="sidebar-status-card__head"><span>DATA PLANE</span><i :class="dataPlaneStatus.xray_running ? 'is-ok' : 'is-bad'"></i></div>
              <strong>{{ dataPlaneRunningLabel(dataPlaneStatus) }}</strong>
              <small>{{ dataPlaneStatus.management_target || "当前未配置数据面" }}</small>
            </div>
            <div class="sidebar-status-card">
              <div class="sidebar-status-card__head"><span>AI NODE</span><i :class="aiNodeStatus && aiNodeStatus.reachable ? 'is-ok' : 'is-warn'"></i></div>
              <strong>{{ aiNodeStatusLabel() }}</strong>
              <small>{{ (aiNodeStatus && aiNodeStatus.management_target) || "AI 节点未纳管" }}</small>
            </div>
          </div>
        </div>
        <div class="sidebar-footer">
          <span>CONTROL PLANE</span>
          <strong>{{ meta.panel_address || "—" }}</strong>
          <small>{{ meta.timezone_label || "服务器本地时区" }}</small>
        </div>
      </aside>

      <button v-if="isMobile && mobileNavOpen" class="mobile-scrim" type="button" aria-label="关闭导航" @click="mobileNavOpen = false"></button>

      <div class="admin-main">
        <header class="admin-topbar">
          <div class="topbar-leading">
            <button v-if="isMobile" class="icon-button mobile-menu-button" type="button" aria-label="打开控制台导航" @click="toggleMobileNav">
              <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 6h16M4 12h16M4 18h16" /></svg>
            </button>
            <div>
              <p class="breadcrumb">CONTROL CENTER <span>/</span> {{ workspaceTitle.toUpperCase() }}</p>
              <h1>{{ workspaceTitle }}</h1>
              <p>{{ workspaceDescription }}</p>
            </div>
          </div>
          <div class="topbar-actions">
            <div class="refresh-meta">
              <span class="live-dot" :class="{ 'is-busy': dashboardRefreshBusy }"></span>
              <span>{{ dashboardRefreshBusy ? "同步中" : lastRefreshLabel }}</span>
            </div>
            <status-pill :tone="dataPlaneTone" :label="dataPlaneRunningLabel(dataPlaneStatus)" />
            <button class="icon-button" type="button" :aria-label="dashboardRefreshBusy ? '正在刷新' : '刷新数据'" :disabled="dashboardRefreshBusy" @click="refreshNow">
              <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20 11a8.1 8.1 0 0 0-14.9-3M4 5v4h4M4 13a8.1 8.1 0 0 0 14.9 3M20 19v-4h-4" /></svg>
            </button>
            <button v-if="authEnabled" class="topbar-logout" type="button" @click="logout">退出登录</button>
          </div>
        </header>

        <main class="admin-content">
          <div v-if="flash.message" class="admin-notice" :class="`is-${flash.level || 'info'}`" role="status" aria-live="polite">
            <span class="admin-notice__mark" aria-hidden="true">{{ flash.level === "error" ? "!" : "i" }}</span>
            <span>{{ flash.message }}</span>
            <button class="notice-close" type="button" aria-label="关闭提示" @click="clearFlash">关闭</button>
          </div>

          <n-spin :show="loading">
            <section v-if="activeWorkspace === 'overview'" class="workspace-view">
              <overview-section />
            </section>
            <section v-if="activeWorkspace === 'routing'" class="workspace-view">
              <ai-routing-section />
            </section>
            <section class="workspace-view" :class="{ 'is-hidden': activeWorkspace !== 'traffic' }" :aria-hidden="activeWorkspace !== 'traffic'">
              <traffic-section />
            </section>
            <section class="workspace-view" :class="{ 'is-hidden': activeWorkspace !== 'resources' }" :aria-hidden="activeWorkspace !== 'resources'">
              <ports-section />
            </section>
            <section class="workspace-view" :class="{ 'is-hidden': activeWorkspace !== 'commerce' }" :aria-hidden="activeWorkspace !== 'commerce'">
              <commerce-section />
            </section>
            <section class="workspace-view" :class="{ 'is-hidden': activeWorkspace !== 'infra' }" :aria-hidden="activeWorkspace !== 'infra'">
              <infra-section />
            </section>
            <section class="workspace-view" :class="{ 'is-hidden': activeWorkspace !== 'observe' }" :aria-hidden="activeWorkspace !== 'observe'">
              <monitoring-section />
            </section>
          </n-spin>
        </main>
      </div>
    </div>
  </n-config-provider>
</template>
